import './style.css';
import {steps,initialState,drop,validDrop} from './experiment.js';
import {createLab} from './lab.js';
import {installDragging} from './drag.js';
const icons={water:'<path d="M11 3h10v5l3 5v15H8V13l3-5Z"/><path d="M8 17h16M11 3v-2h10v2M12 21h8"/>',sample:'<path d="M8 9h16v19H8zM7 5h18v4H7zM10 16h12M12 20h8"/>',burner:'<path d="M8 29h16M13 29V18h6v11M16 15c-8-4 0-9 0-13 1 4 9 9 0 13Z"/>',hotfilter:'<path d="m4 4 12 14L28 4ZM16 18v7M10 27h12M7 4V1h18v3"/>',flask:'<path d="M12 2h8M13 2v10L5 26q-1 3 3 3h16q4 0 3-3l-8-14V2M9 21h14"/>',coldfilter:'<path d="m5 2 11 11L27 2ZM16 13v5M10 20v5l-3 4h18l-3-4v-5M9 7h14"/>',product:'<ellipse cx="16" cy="23" rx="13" ry="5"/><path d="m10 20 3-8 5 7 3-6 3 8M3 23v3q13 8 26 0v-3"/>'};
icons.beaker=icons.flask;icons.paper=icons.product;
const names={water:'Water bottle',sample:'Loaded spatula',beaker:'Beaker',burner:'Burner & tripod',hotfilter:'Hot funnel',flask:'Receiving flask',coldfilter:'Cold funnel',paper:'Wet filter paper',product:'Drying dish',cooling:'Cooling mat'};
document.querySelector('#app').innerHTML=`
<header><div class="brand"><svg viewBox="0 0 32 38" fill="none" stroke="#708650" stroke-width="2"><path d="M11 3h10M13 3v13L5 30q-2 5 4 5h14q6 0 4-5l-8-14V3"/><path d="M9 24h14M12 29h2M19 27h2"/></svg>bench<span>.</span></div><nav><b>Virtual laboratory</b><span>Organic chemistry</span></nav><div class="header-right"><div class="pill"><i class="dot"></i> Interactive simulation</div><button class="round" id="help" aria-label="Open lab guide">?</button></div></header>
<div class="layout"><aside><div class="eyebrow">Your experiment</div><div class="course">LAB 01 / ORGANIC CHEMISTRY</div><div class="side-title">A little heat.<br>A purer compound.</div><div class="progress-label"><span>Experiment progress</span><span id="percent">0%</span></div><div class="progress"><i id="progress-bar"></i></div><div id="steps"></div><div class="side-note"><strong>◈ &nbsp; Learn by doing</strong>Explore the bench. Follow the science.<br>Drag, drop, and watch it change.</div></aside>
<main class="main"><div class="title-row"><div><div class="breadcrumbs">The chemistry of separation</div><h1>Purification by recrystallization</h1><p class="subtitle">From an impure mixture to pure benzoic acid crystals.</p></div><button class="outline" id="protocol">▤ &nbsp; Lab protocol</button></div>
<div class="workspace"><div class="scene-card"><canvas id="scene" aria-label="Interactive 3D chemistry bench. Drag equipment onto highlighted targets using mouse or touch. Keyboard: focus a source, press Space, then focus a target and press Enter."></canvas><div class="scene-top"><div class="scene-badge"><i class="dot"></i> LIVE LAB &nbsp; / &nbsp; BENCH 01</div><div class="scene-badge" id="temperature">22 °C &nbsp; · &nbsp; Room temperature</div></div><div id="status" class="status" role="status"></div><div id="tooltip"></div><button id="scene-source" class="scene-handle source-handle" aria-label="Drag source"></button><button id="scene-target" class="scene-handle target-handle" aria-label="Drop target"></button><div class="scene-bottom"><div class="scene-help">Drag equipment to use · Drag empty space to look · Pinch / scroll to zoom</div><div class="view-buttons"><button id="zoom-in" aria-label="Zoom in">+</button><button id="zoom-out" aria-label="Zoom out">−</button><button id="reset-view" aria-label="Reset camera">⌖</button></div></div></div>
<section class="guide" aria-live="polite"><div class="step-count"><span id="step-count"></span><span>↗</span></div><div class="guide-icon" id="guide-icon"></div><h2 id="step-title"></h2><p class="description" id="description"></p><div class="hint"><b id="hint-title">YOUR NEXT MOVE</b><span id="hint"></span></div><div class="transfer"><button id="drag-source" class="transfer-source"></button><span aria-hidden="true">→</span><button id="drop-target" class="transfer-target"></button></div><div class="action" id="action" role="status"></div><button class="outline" id="repeat" hidden>↻ Repeat experiment</button><div class="time-note">Simulated lab · accelerated process times</div></section></div>
<section class="equipment"><div class="section-line"><h3>On your bench</h3><span>Drag a tool onto its highlighted destination</span></div><div class="tools">${Object.entries(names).filter(([id])=>['water','sample','beaker','flask','paper'].includes(id)).map(([id,name])=>`<button class="tool" data-drag-source="${id}"><svg viewBox="0 0 32 32" aria-hidden="true">${icons[id]||icons.flask}</svg><span>${name}</span></button>`).join('')}</div></section><div class="footer"><span>◌ &nbsp; Based on Pharmaceutical Organic Chemistry III · Lab 1 & 2</span><span>WATER AS SOLVENT &nbsp; / &nbsp; GRAVITY FILTRATION</span></div></main></div>
<dialog id="protocol-dialog"><div class="eyebrow">Lab 1 & 2 · Practical work</div><h2 style="margin-top:14px">Benzoic acid recrystallization</h2><p>Adapted from your uploaded “Purification Of Organic Compounds” lab, practical work on page 7. This simulation uses a benzoic acid and charcoal mixture.</p><ol><li>Measure <b>50 mL water</b> and add <b>3 spatulas of impure acid</b>.</li><li>Heat the beaker over a flame until the benzoic acid dissolves.</li><li>Filter quickly while hot to remove insoluble charcoal.</li><li>Let the solution cool so benzoic acid crystallizes.</li><li>Collect crystals by cold gravity filtration using fresh paper.</li><li>Let the crystals dry on filter paper.</li></ol><p>Heating, cooling, and drying times are accelerated. The 22 °C and 95 °C readouts are illustrative, not measured values or temperatures specified by the lab. Spatula mass and recovery are not specified, so no yield or measured purity is claimed.</p><p>In a physical lab, use goggles, a coat, and appropriate supervision. Hot glassware and flames require care.</p><button class="outline" id="close-protocol">Back to the bench →</button></dialog>
<dialog id="reset-dialog"><h2>Start a fresh experiment?</h2><p>This clears the current mixture and your progress.</p><button class="outline" id="cancel-reset">Keep working</button><button class="outline" id="confirm-reset" style="margin-right:10px">Start again</button></dialog>`;
let state=initialState(),busy=false;let lab;let timer;const $=id=>document.getElementById(id);
function notify(message){$('status').textContent=message;$('status').classList.add('show');clearTimeout(timer);timer=setTimeout(()=>$('status').classList.remove('show'),4500);}
function render(){const s=steps[state.step],count=state.completed?7:state.step;const percent=Math.round(count/7*100);$('percent').textContent=percent+'%';$('progress-bar').style.width=percent+'%';$('steps').innerHTML=steps.map((s,i)=>`<div class="step ${i<count?'done':i===state.step&&!state.completed?'active':''}"><span class="step-num">${i<count?'✓':String(i+1).padStart(2,'0')}</span>${s.short}</div>`).join('');$('step-count').textContent=state.completed?'EXPERIMENT COMPLETE':`STEP ${String(state.step+1).padStart(2,'0')} OF 07`;$('guide-icon').innerHTML=state.completed?'✓':`<svg width="25" height="28" viewBox="0 0 32 32" fill="none" stroke="currentColor" stroke-width="1.5">${icons[s.tool]}</svg>`;$('step-title').textContent=state.completed?'A clearer result.':s.title;$('description').textContent=state.completed?'You separated insoluble charcoal and recovered benzoic acid by changing its solubility in water. Your dried crystals are waiting on the bench.':s.description;$('hint-title').textContent=state.completed?'WHAT YOU LEARNED':'YOUR NEXT MOVE';$('hint').textContent=state.completed?'Hot water dissolves benzoic acid. Filtration removes charcoal. Cooling brings the crystals back.':s.hint+(state.step===1?` (${state.scoops}/3 spatulas added)`:'');$('action').textContent=state.completed?'Experiment complete':'Drag to perform this step';
 $('action').dataset.busy=String(busy);$('repeat').hidden=!state.completed;
 for(const id of ['drag-source','scene-source']){const el=$(id);el.dataset.dragSource=s.source;el.textContent=(id==='scene-source'?'↗ ':'')+names[s.source];el.hidden=state.completed;el.disabled=busy;el.setAttribute('aria-label','Pick up '+names[s.source]);}
 for(const id of ['drop-target','scene-target']){const el=$(id);el.dataset.dropTarget=s.target;el.textContent=(id==='scene-target'?'↓ ':'')+names[s.target];el.hidden=state.completed;el.disabled=busy;el.setAttribute('aria-label','Drop onto '+names[s.target]);}
 document.querySelectorAll('.tool').forEach(b=>{b.classList.toggle('selected',!state.completed&&b.dataset.dragSource===s.source);b.disabled=busy||state.completed;});$('temperature').textContent=state.step===3||state.step===4?'95 °C · Hot solution (simulated)':'22 °C · Room temperature';lab?.update(state,busy);}
async function interact(source,target){
 if(busy)return;
 if(!validDrop(state,source,target)){notify(state.completed?'Experiment complete. Repeat to start again.':`Drop ${names[steps[state.step].source]} onto ${names[steps[state.step].target]}.`);return;}
 const s=steps[state.step],tool=s.tool;busy=true;render();
 const duration={burner:2800,hotfilter:1700,flask:3000,coldfilter:1700,product:2000}[tool]||500;
 $('action').textContent={burner:'Heating…',flask:'Cooling · crystals forming…',product:'Drying crystals…',hotfilter:'Filtering hot solution…',coldfilter:'Collecting crystals…'}[tool]||'Transferring…';
 if(tool==='burner')$('temperature').textContent='Heating · 22 → 95 °C (simulated)';
 if(tool==='flask')$('temperature').textContent='Cooling · 95 → 22 °C (simulated)';
 await new Promise(r=>setTimeout(r,duration));state=drop(state,source,target);busy=false;render();
 notify(tool==='sample'&&state.step===1?`${state.scoops} of 3 spatulas added.`:s.result);
}
try{lab=createLab($('scene'));}catch(error){notify('3D rendering is unavailable. Drag the equipment cards onto the target in the guide to continue.');console.error(error);}
installDragging({canvas:$('scene'),getLab:()=>lab,getState:()=>state,isBusy:()=>busy,onDrop:interact,notify,names});
$('repeat').onclick=()=>$('reset-dialog').showModal();
$('protocol').onclick=$('help').onclick=()=>$('protocol-dialog').showModal();$('close-protocol').onclick=()=>$('protocol-dialog').close();$('cancel-reset').onclick=()=>$('reset-dialog').close();$('confirm-reset').onclick=()=>{clearTimeout(timer);$('status').classList.remove('show');state=initialState();render();lab?.resetView();$('reset-dialog').close();};$('reset-view').onclick=()=>lab?.resetView();$('zoom-in').onclick=()=>lab?.zoom(.85);$('zoom-out').onclick=()=>lab?.zoom(1.15);render();
